### ISSUE TITLE
Alerts (notifications) when components reach certain milestones

### ISSUE THREAD

**Issue by liskin** [liskin/strava-gear#3]
I'd like a way to get notified when a chain/casette/tyre is near its expected lifetime.
This could be implemented as a third report type (`--report=alerts`).

Open question is the configuration UX: do we declare this per-component?
```yaml
components:
  chain11-1:
    name: Shimano CN-HG700-11
    alert-kms: 3000
```

or do we want generic per-bike/role alerts?
```yaml
alerts:
  gravel:
    chain:
      kms: 3000
  road:
    chain:
      kms: 4000
```

Feedback welcome.
